[1a63]
last_change = 1663395162
addr = 6755
func_addr = 6755
comment = "this likely mangles the flag first and then stores it \nin memory here... but it is unclear.\n\nThe correct password is BLACKKEY"
decompiled = false

[1bef]
last_change = 1663395093
addr = 7151
func_addr = 6755
comment = "start the check byte-by-byte. The value loaded into\n`b` is the correct flag byte after its been mangled"
decompiled = false

[1c41]
last_change = 1663395050
addr = 7233
func_addr = 6755
comment = "\nthis is the valid check return\nwhich returns from here"
decompiled = false
